Repository kaivalya98/hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#13 Added Josephus Problem
  CPP/Josephus Problem.cpp
Labels: hacktoberfest

#15 Code For BST(Binary Search Tree)
  C/bst.c
Labels: hacktoberfest-accepted, hacktoberfest

#32 Added problem solution on Bellman Ford Algorithm
  CPP/Negative weight cycle.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#31 Code in C++ language for Swap two strings without using library function
  CPP/swapstrings.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#30 Simple but Pretty Banking game
  Java/BankGame.java
Labels: hacktoberfest-accepted, hacktoberfest

#38 Update README.md
  README.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#57 Add files via upload
  Python/make a pikachu.py
Labels: hacktoberfest-accepted, hacktoberfest

#58 Compare the size of given two arrays
  Python/Python Program to check the size of given two arrays are equal or not.txt
Labels: hacktoberfest-accepted, hacktoberfest
